### ISSUE TITLE
Unique key prop

### ISSUE THREAD

**Issue by omarmung** [jousting-fern/soctionary#52]
bundle.js:1371 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Result`. See https://fb.me/react-warning-keys for more information.
    in Player (created by Result)
    in Result (created by RouterContext)
    in RouterContext (created by Router)
    in Router

**Comment by asutedja** [comment]
This is a normal warning, since react doesn't like it when we use map to create things.  This will get fixed later supposedly.
